
"""the constants used for finding marc field and codes by labels

These are used in the MARCFieldLookup class to allow consumer 
to get a MARC field and subfield by looking up human understandable labels
"""

LOOKUP = [
    {"field": 100,
     "label": "Main Entry - Personal name",
     "subfields": [
         {"code": "a", "label": "Personal name"},
         {"code": "b", "label": "Numeration"},
         {"code": "c", "label": "Title and words associated with name"},
         {"code": "d", "label": "Dates associated with name"},
         {"code": "e", "label": "Relator term"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "j", "label": "Attribution qualifier"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "p", "label": "Name of part/section work"},
         {"code": "q", "label": "Fuller form of name"},
         {"code": "t", "label": "Title of a work"},
         {"code": "u", "label": "Affiliation"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "REal World Object URI"},
         {"code": "4", "label": "Relationship"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"field": 110,
     "label": "Main Entry - Corporate Name",
     "subfields": [
         {"code": "a", "label": "Corporate name or jurisdiction name as entry element"},
         {"code": "b", "label": "Subordinate unit"},
         {"code": "c", "label": "Location of meeting"},
         {"code": "d", "label": "Date of meeting or treaty signing"},
         {"code": "e", "label": "Relator term"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "l", "label": "Language of a work"},
         {"code": "n", "label": "Number of part/section/meeting"},
         {"code": "p", "label": "Name of part/section of a work"},
         {"code": "t", "label": "Title of a work"},
         {"code": "u", "label": "Affiliation"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence identifier"}
     ]
     },
    {"field": 111,
     "label": "Main Entry - Meeting Name",
     "subfields": [
         {"code": "a", "label": "Meeting name or jurisdiction name as entry element"},
         {"code": "b", "label": "Location of meeting"},
         {"code": "d", "label": "Date of meeting or treaty signing"},
         {"code": "e", "label": "Subordinate unit"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "n", "label": "Number of part/section/meeting"},
         {"code": "p", "label": "Name of a part/section of a work"},
         {"code": "q", "label": "Name of meeting following jurisdiction name entry element"},
         {"code": "t", "label": "Title of a work"},
         {"code": "u", "label": "Affiliation"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"field": 130,
     "label": "Main Entry - Uniform Title",
     "subfields": [
         {"code": "a", "label": "Uniform title"},
         {"code": "d", "label": "Date of treaty signing"},
         {"code": "f", "label": "Date of work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "h", "label": "Medium"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "m", "label": "Medium of performance for music"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "o", "label": "Arranged statement for music"},
         {"code": "p", "label": "Name of part/section of a work"},
         {"code": "r", "label": "Key for music"},
         {"code": "s", "label": "Version"},
         {"code": "t", "label": "Title of a work"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"field": 210,
     "label": "Abbreviated Title",
     "subfields": [
         {"code": "a", "label": "Abbreviated title"},
         {"code": "b", "label": "Qualifying information"}
     ]
     },
    {"field": 222,
     "label": "Key Title",
     "subfields": [
         {"code": "a", "label": "Key title"},
         {"code": "b", "label": "Qualifying information"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field lnk and sequence number"}
     ]
     },
    {"field": 240,
     "label": "Uniform Title",
     "subfields": [
         {"code": "a", "label": "Uniform title"},
         {"code": "d", "label": "Date of treaty signing"},
         {"code": "f", "label": "Date of work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "h", "label": "Medium"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "m", "label": "Medium of performance for music"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "o", "label": "Arranged statement for music"},
         {"code": "p", "label": "Name of part/section of a work"},
         {"code": "r", "label": "Key for music"},
         {"code": "s", "label": "Version"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 242,
     "label": "Translation of Titlte by Cataloging Agency",
     "subfields": [
         {"code": "a", "label": "Title"},
         {"code": "b", "label": "Remainder of title"},
         {"code": "c", "label": "Statement of responsibility"},
         {"code": "h", "label": "Medium"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "p", "label": "Name of part/section of a work"},
         {"code": "y", "label": "Language of code translated title"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"field": 243,
     "label": "Collection Uniform Title",
     "subfields": [
         {"code": "a", "label": "Uniform title"},
         {"code": "d", "label": "Date of treaty signing"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "h", "label": "Medium"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "m", "label": "Medium of performance music"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "o", "label": "Arrange statement for music"},
         {"code": "p", "label": "Name of part/section of a work"},
         {"code": "r", "label": "Key for music"},
         {"code": "s", "label": "Version"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"field": 245,
        "label": "Title Statement",
        "subfields": [
            {"code": "a", "label": "Title"},
            {"code": "b", "label": "Remainder of title"},
            {"code": "c", "label": "Statement of responsibility, etc."},
            {"code": "f", "label": "Inclusive dates"},
            {"code": "g", "label": "Buk dates"},
            {"code": "h", "label": "Medium"},
            {"code": "k", "label": "Form"},
            {"code": "n", "label": "Number of part/section of a work"},
            {"code": "p", "label": "Name of part/section of a work"},
            {"code": "s", "label": "Version"},
            {"code": "6", "label": "Linkage"},
            {"code": "8", "label": "Field link and sequence number"}
        ]
     },
    {"field": 246,
        "label": "Varying Form of Title",
        "subfields": [
            {"code": "a", "label": "Title proper/short title"},
            {"code": "b", "label": "Remainder of title"},
            {"code": "f", "label": "Date or sequential designation"},
            {"code": "g", "label": "Miscellaneous information"},
            {"code": "h", "label": "Medium"},
            {"code": "i", "label": "Display text"},
            {"code": "n","label": "Number of part/section of a work"},
            {"code": "p", "label": "Name of part/section of a work"},
            {"code": "5", "label": "Institution to which field applies"},
            {"code": "6", "label": "Linkage"},
            {"code": "8", "label": "Field link and sequence number"},
        ]
     },
    {"field": 247,
        "label": "Former Title",
        "subfields": [
            {"code": "a", "label": "Title proper/short title"},
            {"code": "b", "label": "Remainder of title"},
            {"code": "f", "label": "Date or sequential designation"},
            {"code": "g", "label": "Miscellaneous information"},
            {"code": "h", "label":"Medium"},
            {"code": "n","label": "Number of part/section of a work"},
            {"code": "p", "label": "Name of part/section of a work"},
            {"code": "5", "label": "Institution to which field applies"},
            {"code": "6", "label": "Linkage"},
            {"code": "8", "label": "Field link and sequence number"},
        ]
     },
    {"field": 250,
        "label": "Edition Statement",
        "subfields": [
            {"code": "a", "label": "Editionb statement"},
            {"code": "b", "label": "Remainder of edition statement"},
            {"code": "3", "label": "Materials specified"},
            {"code": "6", "label": "Linkage"},
            {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 254,
     "label": "Musical Presentation Statement",
     "subfield": [
        {"code": "a", "label": "Musical presentation statement"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 255,
     "label": "Cartographic Mathematical Data",
     "subfields": [
         {"code": "a", "label": "Statement of scale"},
         {"code": "b", "label": "Statement of projection"},
         {"code": "c", "label": "Statement of coordinates"},
         {"code": "d", "label": "Statement of zone"},
         {"code": "e", "label": "Statement of equinox"},
         {"code": "f", "label": "Outer G-ring coordinate pairs"},
         {"code": "g", "label": "Exclusion of G-ring coordinate pairs"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 256,
     "label": "Computer File Characteristics",
     "subfields": [
        {"code": "a", "label": "Computer file characteristics"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 257,
     "label": "Country of Producing Entity",
     "subfields": [
        {"code": "a", "label": "country of prudcing entity"},
        {"code": "0", "label": "Authority record control number or standard number"},
        {"code": "1", "label": "Real World Object URI"},
        {"code": "2", "label": "Source"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 258,
     "label": "Philatelic Issue Data",
     "subfields": [
        {"code": "a", "label": "Issuing jurisdiction"},
        {"code": "b", "label": "Denomination"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 260,
     "label": "Publication, Distribution, etc (Imprint)",
     "subfields": [
        {"code": "a", "label": "Publication, distribution, etc."},
        {"code": "b", "label": "Name of publisher, distributor, etc."},
        {"code": "c", "label": "Date of publication, distribution, etc."},
        {"code": "e", "label": "Place of manufacture"},
        {"code": "f", "label": "Manufacturer"},
        {"code": "g", "label": "DAte of manufacture"},
        {"code": "3", "label": "Materials specified"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 263,
     "label": "Projected Publication Date",
     "subfields": [
        {"code": "a", "label": "Projected publication date"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 264,
     "label": "Production, Publication, Distribution, Manufacture, and Copyright Notice",
     "subfields": [
        {"code": "a", "label": "Place of production, publication, distribution, manufacture"},
        {"code": "b", "label": "Name of producer, publisher, distributor, manufacturer"},
        {"code": "c", "label": "Date of production, publication, distribution, manufacture, or copyright notice"}
,
        {"code": "3", "label": "Materials specified"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 270,
     "label": "Address",
     "subfields": [
        {"code": "a", "label": "Address"},
        {"code": "b", "label": "City"},
        {"code": "c", "label": "State or province"},
        {"code": "d", "label": "Country"},
        {"code": "e", "label": "Postal code"},
        {"code": "f", "label": "Terms preceding attention name"},
        {"code": "g", "label": "Attention name"},
        {"code": "h", "label": "Attention position"},
        {"code": "i", "label" : "Type of address"},
        {"code": "j", "label": "Specialized telephone number"},
        {"code": "k", "label": "Telephone number"},
        {"code": "l", "label": "Fax number"},
        {"code": "m", "label": "Electronic mail address"},
        {"code": "n", "label": "TDD or TTY number"},
        {"code": "p", "label": "Contact person"},
        {"code": "q", "label": "Title of contact person"},
        {"code": "r", "label": "Hours"},
        {"code": "z", "label": "Public note"},
        {"code": "4", "label": "Relationship"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 600,
     "label": "Subject Added Entry - Personal Name",
     "subfields": [
        {"code": "a", "label": "Personal name"},
        {"code": "b", "label": "Numeration"},
        {"code": "c", "label": "Titles and other words associated with a name"},
        {"code": "d", "label": "Dates associated with a name"},
        {"code": "e", "label": "Relator term"},
        {"code": "f", "label": "Date of a work"},
        {"code": "g", "label": "Miscellaneous information"},
        {"code": "h", "label": "Medium"},
        {"code": "j", "label": "Attribution qualifier"},
        {"code": "k", "label": "Form subheading"},
        {"code": "l", "label": "Language of a work"},
        {"code": "m", "label": "Mediunm of performance for music"},
        {"code": "n", "label": "Number of part/section of a work"},
        {"code": "p", "label": "Name of part/section of a work"},
        {"code": "q", "label": "Fuller form of a name"},
        {"code": "r", "label": "Key for music"},
        {"code": "s", "label": "Version"},
        {"code": "t", "label": "Title of a work"},
        {"code": "u", "label": "Affiliation"},
        {"code": "v", "label": "Form subdivision"},
        {"code": "x", "label": "General subdvision"},
        {"code": "y", "label": "Chronological subdivision"},
        {"code": "z", "label": "Geographic subdivsion"},
        {"code": "0", "label": "Authority record control number or standard number"{,
        {"code": "1", "label": "Real World Object URI"},
        {"code": "2", "label": "Source of heading or term"},
        {"code": "3", "label": "Materials specified"},
        {"code": "4", "label": "Relationship"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {
        "field": 610,
        "label": "Subject Added Entry - Corporate Name",
        "subfields": [
            {"code": "a", "label": "Corporate name or jurisdiction name as entry element"},
            {"code": "b", "label": "Subordinate unit"},
            {"code": "c", "label": "Location of meeting"},
            {"code": "d", "label": "Date of meeting or treaty signing"},
            {"code": "e", "label": "Relator term"},
            {"code": "f", "label": "Date of a work"},
            {"code": "g", "label": "Miscellaneous information"},
            {"code": "h", "label": "Medium"},
            {"code": "k", "label":  "Form subheading"},
            {"code": "l", "label": "Language of a work"},
            {"code": "m", "label": "Medium of performance for music"},
            {"code": "n", "label": "Number of part/section/meeting"},
            {"code": "o", "label": "Arranged statement for music"},
            {"code": "p", "label": "Name of part/section of a work"},
            {"code": "r", "label": "Key for music"},
            {"code": "s", "label": "Version"},
            {"code": "t", "label": "Title of a work"},
            {"code": "u", "label": "Affiliation"},
            {"code": "v", "label": "Form subdivision"},
            {"code": "x", "label": "General subdivision"},
            {"code": "y", "label": "Chronological subdivision"},
            {"code": "z", "label": "Geographic subdivision"},
            {"code": "0", "label": "Authority record control number or standard number"{,
            {"code": "1", "label": "Real World Object URI"},
            {"code": "2", "label": "Source of heading or term"},
            {"code": "3", "label": "Materials specified"},
            {"code": "4", "label": "Relationship"},
            {"code": "6", "label": "Linkage"},
            {"code": "8", "label": "Field link and sequence number"}

        ]
    },
    {"field": 611,
     "label": "Subject Added Entry - Meeting Name",
     "subfields": [
        {"code": "a", "label": "Meeting name or jurisdiction name as entry element"},
        {"code": "c", "label": "Location of meeting"},
        {"code": "d", "label": "Date of meeting or treaty signing"},
        {"code": "e", "label": "Subordinate unit"},
        {"code": "f", "label": "Date of a work"},
        {"code": "g", "label": "Miscellaneious information"},
        {"code": "h", "label": "Medium"},
        {"code": "j", "label": "Relator term"},
        {"code": "k", "label": "Form subheading"},
        {"code": "l", "label": "Language of a work"},
        {"code": "n", "label": "Number of part/section of a work"},
        {"code": "p", "label": "Name of part/section of a work"},
        {"code": "q", "label": "Name of meeting following jurisdiction name entry element"},
        {"code": "s", "label": "Version"},
        {"code": "t", "label": "title of a work"},
        {"code": "u", "label": "Affiliation"},
        {"code": "v", "label": "Form subdivision"},
        {"code": "x", "label": "General subdivision"},
        {"code": "y", "label": "Chronological subdivision"},
        {"code": "z", "label": "Geopgraphic subdivision"},
        {"code": "0", "label": "Authority record control number or standard number"},
        {"code": "1", "label": "Real World Object URI"},
        {"code": "2", "label": "Source of heading or term"},
        {"code": "3", "label": "Materials specified"},
        {"code": "4", "label": "Relationship"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 630,
     "label": "Subject Added Entry - Uniform Title",
     "subfields": []
     },
    {"field": 647,
     "label": "Subject Added Entry - Named Event",
     "subfields": []
     },
    {"field": 648,
     "label": "Subject Added Entry - Chronological Term",
     "subfields": []
     },
    {"field": 650,
     "label": "Subject Added Entry = Topical Term",
     "subfields": []
     },
    {"field": 651,
     "label": "Subject Added Entry - Geographic Name",
     "subfields": []
     },
    {"field": 653,
     "label": "Index Term - Uncontrolled",
     "subfields": []
     },
    {"field": 654,
     "label": "Subject Added Entry - Faceted Topical Term",
     "subfields": []
     },
    {"field": 655,
     "label": "Index Term - Genre/Form",
     "subfields": []
     },
    {"field": 656,
     "label": "Index Term - Occupation",
     "subfields": []
     },
    {"field": 657,
     "label": "Index Term - Function",
     "subfields": []
     },
    {"field": 658,
     "label": "Index Term - Curriculum Objective",
     "subfields": []
     },
    {"field": 662,
     "label": "Subject Added Entry - Hierarchical Place Name",
     "subfields": []
     },
    {"field": 690,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 691,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 692,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 693,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 694,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 695,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 696,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 697,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 698,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 699,
     "label": "Local Subject",
     "subfields": []
     },
    {"field": 700,
     "label": "Added Entry - Personal Name",
     "subfields": []
     },
    {"field": 710,
     "label": "Added Entry - Corporate Name",
     "subfields": []
     },
    {"field": 711,
     "label": "Added Entry - Meeting Name",
     "subfields": []
     },
    {"field": 720,
     "label": "Added Entry - Uncontrolled Name",
     "subfiled": []
     },
    {"field": 730,
     "label": "Added Entry - Uniform Title",
     "subfields": []
     },
    {"field": 740,
     "label": "Added Entry - Uncontrolled Related/Analytical Title",
     "subfields": []
     },
    {"field": 751,
     "label": "Added Entry - Geographic Name",
     "subfields": []
     },
    {"field": 752,
     "label": "Added Entry - Hierarchical Place Name",
     "subfields": []
     },
    {"field": 753,
     "label": "System Details Access to Computer File",
     "subfields": []
     },
    {"field": 754,
     "label": "Added Entry - Taxonomic Identification",
     "subfields": []
     },
    {"field": 758,
     "label": "Resource Identifier",
     "subfields": []
     },
    {"field": 760,
     "label": "Main Entry Series Entry",
     "subfieldS": []
     },
    {"field": 762,
     "label": "Subseries Entry",
     "subfields": []
     },
    {"field": 765,
     "label": "Original Language Entry",
     "subfields": []
     },
    {"field": 767,
     "label": "Translation Entry",
     "subfields": []
     },
    {"field": 770,
     "label": "Supplement/Special Issue Entry",
     "subfields": []
     },
    {"field": 772,
     "label": "Supplement Parent Entry",
     "subfields": []
     },
    {"field": 773,
     "label": "Host Item Entry",
     "subfields": []
     },
    {"field": 774,
     "label": "Constituent Unit Entry",
     "subfields": []
     },
    {"field": 775,
     "label": "Other Edition Entry",
     "subfields": []
     },
    {"field": 776,
     "label": "Additional Physical Form Entry",
     "subfields": []
     },
    {"field": 777,
     "label": "Issued With Entry",
     "subfields": []
     },
    {"field": 780,
     "label": "Preceding Entry",
     "subfields": []
     },
    {"field": 785,
     "label": "Succeeding Entry",
     "subfields": []
     },
    {"field": 786,
     "label": "Date Source Entry",
     "subfileds": []
     },
    {"field": 787,
     "label": "Other Relationship Entry",
     "subfields": []
     },
    {"field": 800,
     "label": "Series Added Entry - Personal Name",
     "subfields": []
     },
    {"field": 810,
     "label": "Series Added Entry - Corporate Name",
     "subfields": []
     },
    {"field": 811,
     "label": "Series Added Entry - Meeting Name",
     "subfields": []
     },
    {"field": 830,
     "label": "Series Added Entry - Uniform Title",
     "subfields": [
         {"code": "a", "label": "Uniform title"},
         {"code": "b", "label": "Date of treaty signing"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "m", "label": "Medium of a performance for music"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "o", "label": "Arranged statement for music"},
         {"code": "r", "label": "Key for music"},
         {"code": "s", "label": "Version"},
         {"code": "t", "label": "Title of a work"},
         {"code": "v", "label": "Volume/sequential designation"},
         {"code": "w", "label": "Bibliographic record control number"},
         {"code": "x", "label": "International Standard Serial Number"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code": "3", "label": "Materials specified"},
         {"code": "5", "label": "Institution to which field applies"},
         {"code": "7", "label": "Control subfield"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"841": "Holdings Coded Data Values"
     },
    {"field": 842,
     "label": "Textual Physical form Designator",
     "subfields": []
     },
    {"field": 843,
     "label": "Reproduction Note",
     "subfields": []
     },
    {"field": 844,
     "label": "Name of Unit",
     "subfields": []
     },
    {"field": 845,
     "label": "Terms Governing Use and Reproduction",
     "subfields": []
     },
    {"field": 850,
     "label": "Holding Institution",
     "subfields": [
        {"code": "a", "label": "Holding institution",
         "code": "8", "label": "Field link and sequence number"}
     ]
     },
    {"field": 852,
     "label": "Location",
     "subfields": [
        {"code": "a", "label": "Location"},
        {"code": "b", "label": "Sublocation or collection"},
        {"code": "c", "Label": "Shelving location"},
        {"code": "d", "label": "Former shelving location"},
        {"code": "e", "label": "Address"},
        {"code": "f", "label": "Coded location qualifier"},
        {"code": "g", "label": "Non-coded location qualifier"},
        {"code": "h", "label": "Classification part"},
        {"code": "i", "label": "Item part"},
        {"code": "j", "label": "Shelving control number"},
        {"code": "k", "label": "Call number prefix"},
        {"code": "l", "label": "Shelving form of title"},
        {"code": "m", "label": "Call number suffix"},
        {"code": "n", "label": "Country code"},
        {"code": "p", "label": "Piece designation"},
        {"code": "q", "label": "Piece physical condition"},
        {"code": "s", "label": "Coyright article"},
        {"code": "t", "label": "Copy number"},
        {"code": "u", "label": "Uniform Resource Identifier"},
        {"code": "x", "label": "Nonpublic note"},
        {"code": "z", "label": "Public note"},
        {"code": "2", "label": "Source of classification or shelving scheme"},
        {"code": "3", "label": "Material specified"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Sequence number"}
     ]
     },
    {"field": 853,
     "label": "Captions and Pattern - Basic Bibliographic Unit",
     "subfields": []
     },
    {"field": 854,
     "label": "Captions and Pattern - Supplementary Material",
     "subfields": []
     },
    {"field": 855,
     "label": "Captions and Pattern - Indexes",
     "subfields": []
     },
    {"field": 856,
     "label": "Electronic Location and Access",
     "subfields": [
         {"code": "a", "label": "Host name"},
         {"code": "b", "label": "Access number"},
         {"code": "c", "label": "Compression information"},
         {"code": "d", "label": "Path"},
         {"code": "f", "label": "Electronic name"},
         {"code": "h", "label": "Processor of request"},
         {"code": "i", "label": "Instruction"},
         {"code": "j", "label": "Bits per second"},
         {"code": "k", "label": "Password"},
         {"code": "m", "label": "Contact for access assistance"},
         {"code": "n", "label": "Name of location host"},
         {"code": "o", "label": "Operating system"},
         {"code": "p", "label": "Port"},
         {"code": "q", "label": "Electronic format"},
         {"code": "r", "label": "Settings"},
         {"code": "s", "label": "Settings"},
         {"code": "t", "label": "Terminal emulation"},
         {"code": "u", "label": "Uniform Resource Identifier"},
         {"code": "v", "label": "Hours access method available"},
         {"code": "w", "label": "Record control number"},
         {"code": "x", "label": "Nonpublic note"},
         {"code": "y", "label": "Link text"},
         {"code": "z", "label": "Public note"},
         {"code": "2", "label": "Access method"},
         {"code": "3", "label": "Materials specified"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "Label": "Field link and sequence number"}
     ]
     },
    {"field": 863,
     "label": "Enumeration and Chronology- Basic Bibligraphic Unit",
     "subfields": []
     },
    {"field": 864,
     "label": "Enumeration and Chronology - Supplementary Material",
     "subfields": []
     },
    {"field": 865,
     "label": "Enumeration and Chronology - Indexes",
     "subfields": []
     },
    {"field": 866,
     "label": "Textual Holdings - Basic Bibliographic Unit",
     "subfields": []
     },
    {"field": 867,
     "label": "Textual Holdings - Supplementary Material",
     "subfields": []
     },
    {"field": 868,
     "label": "Textual Holdings - Indexes",
     "subfields": []
     },
    {"field": 876,
     "label": "Item Information - Basic Bibliographic Unit",
     "subfields": []
    },
    {"field": 877,
     "label": "Item Information - Basic Bibliographic Unit",
     "subfields": []
    },
    {"field": 878,
     "label": "Item Information - Indexes",
     "subfields": []
    },
    {"field": 880,
     "label": "Alternate Graphic Representation",
     "subfields": [
        {"code": "a", "label": "Same as associated field"},
        {"code": "b", "label": "Same as associated field"},
        {"code": "c", "label": "Same as associated field"},
        {"code": "d", "label": "Same as associated field"},
        {"code": "e", "label": "Same as associated field"},
        {"code": "f", "label": "Same as associated field"},
        {"code": "g", "label": "Same as associated field"},
        {"code": "h", "label": "Same as associated field"},
        {"code": "i", "label": "Same as associated field"},
        {"code": "j", "label": "Same as associated field"},
        {"code": "k", "label": "Same as associated field"},
        {"code": "l", "label": "Same as associated field"},
        {"code": "m", "label": "Same as associated field"},
        {"code": "n", "label": "Same as associated field"},
        {"code": "o", "label": "Same as associated field"},
        {"code": "p", "label": "Same as associated field"},
        {"code": "q", "label": "Same as associated field"},
        {"code": "r", "label": "Same as associated field"},
        {"code": "s", "label": "Same as associated field"},
        {"code": "t", "label": "Same as associated field"},
        {"code": "u", "label": "Same as associated field"},
        {"code": "v", "label": "Same as associated field"},
        {"code": "w", "label": "Same as associated field"},
        {"code": "x", "label": "Same as associated field"},
        {"code": "y", "label": "Same as associated field"},
        {"code": "z", "label": "Same as associated field"},
        {"code": "0", "label": "Same as associated field"},
        {"code": "1", "label": "Same as associated field"},
        {"code": "2", "label": "Same as associated field"},
        {"code": "3", "label": "Same as associated field"},
        {"code": "4", "label": "Same as associated field"},
        {"code": "5", "label": "Same as associated field"},
        {"code": "6", "label": "Linkage"},
        {"code": "7", "label": "Same as associated field"},
        {"code": "8", "label": "Same as associated field"},
        {"code": "9", "label": "Same as associated field"}
     ]
    },
    {"field": 882,
     "label": "Replacement Record Information",
     "subfields": [
        {"code": "a", "label": "Replacement title"},
        {"code": "i", "label": "Explanatory text"},
        {"code": "w", "label": "Replacement bibliographic record control number"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 883,
     "label": "Machine-Generated Metadata Provenance",
     "subfields": [
        {"code": "a", "label": "Generation process"},
        {"code": "c", "label": "Confidence value"},
        {"code": "d", "label": "Generation date"},
        {"code": "q", "label": "Generation agency"},
        {"code": "x", "label": "Validity end date"},
        {"code": "u", "label": "Uniform Resource Identifier"},
        {"code": "w", "label": "Bibliographic record control number"},
        {"code": "0", "label": "Authority record control number or standard number"},
        {"code": "1", "label": "Real World Object URI"},
        {"code": "8", "label": "Field link and sequence number"},
    ]
    },
    {"field": 884,
     "label": "Description Conversion Information",
     "subfields": [
        {"code": "a", "label": "Conversion process"},
        {"code": "g", "label": "Conversion title"},
        {"code": "k", "label": "Identifier of source metadata"},
        {"code": "q", "label": "Conversion agency"},
        {"code": "u", "label": "Uniform Resource Identifier"}
     ]
    },
    {"field": 885,
     "label": "Matching Information",
     "subfields": [
        {"code": "a", "label": "Matching information"},
        {"code": "b", "label": "Status of matching and its checking"},
        {"code": "c", "label": "Confidence value"},
        {"code": "d", "label": "Generation date"},
        {"code": "w", "label": "Record control number"},
        {"code": "x", "label": "Nonpublic note"},
        {"code": "z", "label": "Public note"},
        {"code": "0", "label": "Authority record control number or standard number"},
        {"code": "1", "label": "Real World Object URI"},
        {"code": "2", "label": "Source"},
        {"code": "5", "label": "Instution to which field applies"},
     ]
    },
    {"field": 886,
     "label": "Foreign MARC Information Field",
     "subfields": [
        {"code": "a", "label": "Same as associated field"},
        {"code": "b", "label": "Same as associated field"},
        {"code": "c", "label": "Same as associated field"},
        {"code": "d", "label": "Same as associated field"},
        {"code": "e", "label": "Same as associated field"},
        {"code": "f", "label": "Same as associated field"},
        {"code": "g", "label": "Same as associated field"},
        {"code": "h", "label": "Same as associated field"},
        {"code": "i", "label": "Same as associated field"},
        {"code": "j", "label": "Same as associated field"},
        {"code": "k", "label": "Same as associated field"},
        {"code": "l", "label": "Same as associated field"},
        {"code": "m", "label": "Same as associated field"},
        {"code": "n", "label": "Same as associated field"},
        {"code": "o", "label": "Same as associated field"},
        {"code": "p", "label": "Same as associated field"},
        {"code": "q", "label": "Same as associated field"},
        {"code": "r", "label": "Same as associated field"},
        {"code": "s", "label": "Same as associated field"},
        {"code": "t", "label": "Same as associated field"},
        {"code": "u", "label": "Same as associated field"},
        {"code": "v", "label": "Same as associated field"},
        {"code": "w", "label": "Same as associated field"},
        {"code": "x", "label": "Same as associated field"},
        {"code": "y", "label": "Same as associated field"},
        {"code": "z", "label": "Same as associated field"},
        {"code": "0", "label": "Same as associated field"},
        {"code": "1", "label": "Same as associated field"},
        {"code": "2", "label": "Same as associated field"},
        {"code": "3", "label": "Same as associated field"},
        {"code": "4", "label": "Same as associated field"},
        {"code": "5", "label": "Same as associated field"},
        {"code": "6", "label": "Linkage"},
        {"code": "7", "label": "Same as associated field"},
        {"code": "8", "label": "Same as associated field"},
        {"code": "9", "label": "Same as associated field"}
 
     ]
    },
    {"field": 887,
     "label": "Non-MARC Information Field",
     "subfields": []
    }
]
