
LOOKUP = [
    {"field": 100, 
     "label": "Main Entry - Personal name",
     "subfields": [
         {"code": "a", "label": "Personal name"},
         {"code": "b", "label": "Numeration"},
         {"code": "c", "label": "Title and words associated with name"},
         {"code": "d", "label": "Dates associated with name"},
         {"code": "e", "label": "Relator term"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "j", "label": "Attribution qualifier"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "p", "label": "Name of part/section work"},
         {"code": "q", "label": "Fuller form of name"},
         {"code": "t", "label": "Title of a work"},
         {"code": "u", "label": "Affiliation"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "REal World Object URI"},
         {"code": "4", "label": "Relationship"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ] 
    },
    {"field": 110,
    "label": "Main Entry - Corporate Name",
    "subfields": [
        {"code": "a", "label": "Corporate name or jurisdiction name as entry element"},
        {"code": "b", "label": "Subordinate unit"},
        {"code": "c", "label": "Location of meeting"},
        {"code": "d", "label": "Date of meeting or treaty signing"},
        {"code": "e", "label": "Relator term"},
        {"code": "f", "label": "Date of a work"},
        {"code": "g", "label": "Miscellaneous information"},
        {"code": "l", "label": "Language of a work"},
        {"code": "n", "label": "Number of part/section/meeting"},
        {"code": "p", "label": "Name of part/section of a work"},
        {"code": "t", "label": "Title of a work"},
        {"code": "u", "label": "Affiliation"},
        {"code": "0", "label": "Authority record control number or standard number"},
        {"code": "1", "label": "Real World Object URI"},
        {"code": "6", "label": "Linkage"},
        {"code": "8", "label": "Field link and sequence identifier"}
    ]
    },
    {"field": 111,
     "label": "Main Entry - Meeting Name",
     "subfields": [
         {"code": "a", "label": "Meeting name or jurisdiction name as entry element"},
         {"code": "b", "label": "Location of meeting"},
         {"code": "d", "label": "Date of meeting or treaty signing"},
         {"code": "e", "label": "Subordinate unit"},
         {"code": "f", "label": "Date of a work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "n", "label": "Number of part/section/meeting"},
         {"code": "p", "label": "Name of a part/section of a work"},
         {"code": "q", "label": "Name of meeting following jurisdiction name entry element"},
         {"code": "t", "label": "Title of a work"},
         {"code": "u", "label": "Affiliation"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code": "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 130,
     "label": "Main Entry - Uniform Title",
     "subfields": [
         {"code": "a", "label": "Uniform title"},
         {"code": "d", "label": "Date of treaty signing"},
         {"code": "f", "label": "Date of work"},
         {"code": "g", "label": "Miscellaneous information"},
         {"code": "h", "label": "Medium"},
         {"code": "k", "label": "Form subheading"},
         {"code": "l", "label": "Language of a work"},
         {"code": "m", "label": "Medium of performance for music"},
         {"code": "n", "label": "Number of part/section of a work"},
         {"code": "o", "label": "Arranged statement for music"},
         {"code": "p", "label": "Name of part/section of a work"},
         {"code": "r", "label": "Key for music"},
         {"code": "s", "label": "Version"},
         {"code": "t", "label": "Title of a work"},
         {"code": "0", "label": "Authority record control number or standard number"},
         {"code": "1", "label": "Real World Object URI"},
         {"code" "6", "label": "Linkage"},
         {"code": "8", "label": "Field link and sequence number"}
     ]
    },
    {"field": 210,
     "label": "Abbreviated Title",
     "subfields": []
    },
    {"field": 222,
    "label": "Key Title",
    "subfields": []
    },
    {"field": 240, 
     "label": "Uniform Title",
     "subfields": []
     },
     {"field": 242, 
      "label": "Translation of Titlte by Cataloging Agency",
      "subfields": []
      },
      {"field": 243,
       "label": "Collection Uniform Title",
       "subfields": []
       },
       {"field": 245,
        "label": "Title Statement",
        "subfields": []
       },
       {"field": 246,
        "label": "Varying Form of Title",
        "subfields": []
       },
       {"field": 247,
        "label": "Former Title",
        "subfields": []
       },
       {"field": 250,
        "label": "Edition Statement",
        "subfields": []
        },
        {"field": 254,
         "label": "Musical Presentation Statement",
         "subfield": []
         },
         {"field": 255,
          "label": "Cartographic Mathematical Data",
          "subfields": []
         },
         {"field": 256,
          "label": "Computer File Characteristics",
          "subfields": []
         },
         {"field": 257,
          "label": "Country of Producing Entity",
          "subfields": []
         },
         {"field": 258,
          "label": "Philatelic Issue Data",
          "subfields": []
         },
         {"field": 260,
          "label": "Publication, Distribution, etc (Imprint)",
          "subfields": []
         },
         {"field": 263,
          "label": "Projected Publication Date",
          "subfields": []
         },
         {"field": 264,
          "label": "Production, Publication, Distribution, Manufacture, and Copyright Notice",
          "subfields": []
         },
         {"field": 270,
          "label": "Address",
          "subfields": []
         },
         {"field": 600
          "label": "Subject Added Entry - Personal Name",
          "subfields": []
         },
         {
          "field": 610
          "label": "Subject Added Entry - Corporate Name",
          "subfields": []
         },
        {"field": 611,
         "label": "Subject Added Entry - Meeting Name",
         "subfields": []
        },
        {"field": 630
         "label": "Subject Added Entry - Uniform Title",
         "subfields": []
        },
        {"field": 647,
         "label": "Subject Added Entry - Named Event",
         "subfields": []
        },
        {"field": 648,
         "label": "Subject Added Entry - Chronological Term",
         "subfields": []
        },
        {"field": 650,
         "label": "Subject Added Entry = Topical Term",
         "subfields": []
        },
        {"field": 651,
         "label": "Subject Added Entry - Geographic Name",
         "subfields": []
        }
    "653": "Index Term - Uncontrolled",
    "654": "Subject Added Entry - Faceted Topical Term",
    "655": "Index Term - Genre/Form",
    "656": "Index Term - Occupation",
    "657": "Index Term - Function",
    "658": "Index Term - Curriculum Objective",
    "662": "Subject Added Entry - Hierarchical Place Name",
    "690": "Local Subject",
    "691": "Local Subject",
    "692": "Local Subject",
    "693": "Local Subject",
    "694": "Local Subject",
    "695": "Local Subject",
    "696": "Local Subject",
    "697": "Local Subject",
    "698": "Local Subject",
    "699": "Local Subject",
    "700": "Added Entry - Personal Name",
    "710": "Added Entry - Corporate Name",
    "711": "Added Entry - Meeting Name",
    "720": "Added Entry - Uncontrolled Name",
    "730": "Added Entry - Uniform Title",
    "740": "Added Entry - Uncontrolled Related/Analytical Title",
    "751": "Added Entry - Geographic Name",
    "752": "Added Entry - Hierarchical Place Name",
    "753": "System Details Access to Computer File",
    "754": "Added Entry - Taxonomic Identification",
    "758": "Resource Identifier",
    "760": "Main Entry Series Entry",
    "762": "Subseries Entry",
    "765": "Original Language Entry",
    "767": "Translation Entry",
    "770": "Supplement/Special Issue Entry",
    "772": "Supplement Parent Entry",
    "773": "Host Item Entry",
    "774": "Constituent Unit Entry",
    "775": "Other Edition Entry",
    "776": "Additional Physical Form Entry",
    "777": "Issued With Entry",
    "780": "Preceding Entry",
    "785": "Succeeding Entry",
    "786": "Date Source Entry",
    "787": "Other Relationship Entry",
    "800": "Series Added Entry - Personal Name",
    "810": "Series Added Entry - Corporate Name",
    "811": "Series Added Entry - Meeting Name",
    "830": "Series Added Entry - Uniform Title",
    "841": "Holdings Coded Data Values",
    "842": "Textual Physical form Designator",
    "843": "Reproduction Note",
    "844": "Name of Unit",
    "845": "Terms Governing Use and Reproduction",
    "850": "Holding Institution",
    "852": "Location",
    "853": "Captions and Pattern - Basic Bibliographic Unit",
    "854": "Captions and Pattern - Supplementary Material",
    "855": "Captions and Pattern - Indexes",
    "856": "Electronic Location and Access",
    "863": "Enumeration and Chronology- Basic Bibligraphic Unit",
    {"field": 864": "Enumeration and Chronology - Supplementary MAterial",
    {"field": 865,
     "label": "Enumeration and Chronology - Indexes",
     "subfields": []
    },
    {"field": 866,
     "label": "Textual Holdings - Basic Bibliographic Unit",
     "subfields": []
    },
    {"field": 867
     "label": "Textual Holdings - Supplementary Material",
     "subfields": []
    },
    {"field": 868,
     "label": "Textual Holdings - Indexes",
     "subfields": []
    }
]